name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/compilar-y-desplegar.yml'
      - 'GithubActionsDemoApp/**'
      - 'Pruebas/**'
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: instalar .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x
          
      - name: Obteninedo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

        
      
